var gfc_bo=osapi,gfc_co="ceil";gfc_1[gfc_].wi=gfc_Bd(21,function(a,b,c){return a?c<b?[]:a[gfc_Gc](gfc_d.min(b,a[gfc_B]),gfc_d.min(c,a[gfc_B])):[]});gfc_1[gfc_].share=gfc_Bd(19,function(){gfc_yn();return!1});gfc_1[gfc_].yf=gfc_Bd(17,function(){return this.Gb.pop()});gfc_1[gfc_].Xi=gfc_Bd(16,function(){var a=this.yd;a.valid?(this.d=this.Gg(this.yd),this.Zh(a[gfc_hd])):(this.yd=null,this.render(a.actions,a[gfc_hd],a.params));this.Fg()});
gfc_oa(gfc_N[gfc_],gfc_Bd(3,function(){this.x=gfc_d[gfc_co](this.x);this.y=gfc_d[gfc_co](this.y);return this}));gfc_oa(gfc_Cf[gfc_],gfc_Bd(2,function(){gfc_ma(this,gfc_d[gfc_co](this[gfc_i]));gfc_Ga(this,gfc_d[gfc_co](this[gfc_u]));return this}));gfc_oa(gfc_wh[gfc_],gfc_Bd(1,function(){this.top=gfc_d[gfc_co](this.top);gfc_Ha(this,gfc_d[gfc_co](this[gfc_wc]));gfc_Da(this,gfc_d[gfc_co](this[gfc_gc]));gfc_Na(this,gfc_d[gfc_co](this[gfc_z]));return this}));
gfc_oa(gfc_yh[gfc_],gfc_Bd(0,function(){gfc_Na(this,gfc_d[gfc_co](this[gfc_z]));this.top=gfc_d[gfc_co](this.top);gfc_ma(this,gfc_d[gfc_co](this[gfc_i]));gfc_Ga(this,gfc_d[gfc_co](this[gfc_u]));return this}));
var gfc_do=function(a){return a=gfc_b[gfc_md]+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ha();this.Br();var d=new gfc_R;d.set("members",{action:this.Lu,callback:this.Ht});d.set("member-page",{action:this.Ku,callback:this.Gt});d.set("blocked-member-page",{action:this.Eu,callback:this.Ct});d.set("profile-friends-page",{action:this.Qu,callback:this.Lt});d.set("sitesData",{action:this.Yu,callback:this.Pt});d.set("viewerFriends",{action:this.cv,callback:this.Rt});d.set("profileData",
{action:this.Pu,callback:this.Kt});d.set("blockUser",{action:this.Du,callback:this.Bt});d.set("unblockUser",{action:this.av,callback:this.Qt});d.set("profileFriends",{action:this.Ru,callback:this.Mt});d.set("activityData",{action:this.Jf,callback:this.hd});d.set("sendFriendRequest",{action:this.Xu,callback:this.Ot});d.set("sendFriendRequestResponse",{action:this.Hu,callback:this.nm});d.set("deleteActivity",{action:this.Kf,callback:this.hd});d.set("requestAndProcessViewerNumWaitingMessages",{action:this.dv,
callback:this.Tt});d.set("requestPromo",{action:this.Su,callback:this.Nt});this.lb=null;this.Hx=new gfc_Gn("fc-members-options-menu",gfc_K(this.et,this),gfc_K(this.dt,this),gfc_K(this.ft,this),0,gfc_b[gfc_md],this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.nw=!1;this.Ba=10;this.rf=15;this.tn=10;var e=gfc_4h(gfc_Jh()),f=gfc_eo;this.Ub=3;this.rc=8;this.Pm=null;this.la=this.rc*this.Ub;this.slimTopCapHeight=19;this.tinyTopCapHeight=8;this.isMessagingEnabled=a;this.isPromosEnabled=
b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=null;this.Nb=new gfc_Cn;this.Th()&&(a=(a=this.f(f.FACE_SIZE))?gfc_ga(a):32,a+=6,this.Ub=gfc_d[gfc_5a]((e[gfc_i]-10)/a),e=340,e=this.f(f.HEIGHT),(f=this.f(f.NUMBER_ROWS))?(this.rc=gfc_ga(f),e=this.rc*a,this.Pm=e+27):e&&(e=gfc_ga(e)-96,this.rc=gfc_d.max(2,gfc_d[gfc_5a](e/a)),this.Pm=this.rc*a+27),this.la=this.rc*this.Ub);gfc_1[gfc_G](this,d)};gfc_7.inherits(gfc_1);
gfc_Ba(gfc_7[gfc_],function(){gfc_7.i[gfc_t][gfc_G](this);gfc_$m("start");var a=gfc_a[gfc_r][gfc_Qc](),b=gfc_ca();(a=b.profileId||a.profileId)?(b={},b[gfc_e[gfc_x][gfc_q].ID]=a,a=new gfc_e[gfc_x](b),this.render(["profileData","profileFriends","activityData"],"profile",{person:a})):(a=["members","viewerFriends"],this.isMessagingEnabled&&a[gfc_v]("requestAndProcessViewerNumWaitingMessages"),this.isPromosEnabled&&!this.Jb()&&a[gfc_v]("requestPromo"),this.render(a,"faces"))});gfc_7[gfc_].e={};
gfc_7[gfc_].Ha=function(){this.e.MSG_SITE_MEMBERS="Membros";this.e.MSG_BE_THE_FIRST="Seja o primeiro!";this.e.MSG_NO_SITE_MEMBERS="Ainda n\u00e3o h\u00e1 membros.";this.e.MSG_ALL_SITE_MEMBERS="Todos os membros";this.e.MSG_ALL_BLOCKED_MEMBERS="Todos os membros bloqueados";this.e.MSG_NO_BLOCKED_MEMBERS="Voc\u00ea n\u00e3o bloqueou nenhum membro";this.e.MSG_YOUR_FRIENDS="Seus amigos";this.e.MSG_ALL_YOUR_FRIENDS="Todos os seus amigos";this.e.MSG_JFJ="Participe e conecte-se com as pessoas!";this.e.MSG_MANAGE=
"Gerenciar membros";this.e.MSG_SETTINGS="Configura\u00e7\u00f5es";this.e.MSG_OPTIONS="Op\u00e7\u00f5es";this.e.MSG_MEMBERS_SHARE="Compartilhar esta p\u00e1gina";this.e.MSG_BACK="Voltar";this.e.MSG_BACK_TO_TOP="P\u00e1gina inicial";this.e.MSG_VIEW_MY_PROFILE="Visualizar meu perfil";this.e.MSG_ABOUT_ME="Sobre mim";this.e.MSG_MORE="Mais \u00bb";this.e.MSG_SHOW_BLOCKED="Mostrar membros bloqueados \u00bb";this.e.MSG_SHOW_ALL="\u00ab Mostrar todos os membros";this.e.MSG_LINK_IN_NETWORKS="Vincular suas redes sociais";
this.e.MSG_ACTIVITIES="Atividades";this.e.MSG_ALL_ACTIVITIES="Mais atividades";this.e.MSG_DELETE_THIS="Excluir";this.e.MSG_SITES="Sites dos quais eu participo";this.e.MSG_ALL_SITES="Mais sites dos quais eu participo";this.e.MSG_LINKS="Links";this.e.MSG_ALL_LINKS="Mais links";this.e.MSG_NO_ACTIVITIES="Nenhuma atividade a ser exibida";this.e.MSG_ADD_AS_FRIEND="Adicionar como amigo(a)";this.e.MSG_SEND_MESSAGE="Enviar mensagem";this.e.MSG_BLOCK_USER="Bloquear este usu\u00e1rio";this.e.MSG_UNBLOCK_USER=
"Desbloquear este usu\u00e1rio";this.e.MSG_USER_IS_ADMIN="Administrador";this.e.MSG_JOIN="Participar deste site";this.e.MSG_OR="ou";this.e.MSG_SIGN_IN="Fazer login";this.e.MSG_SIGN_OUT="Sair";this.e.MSG_PREVIOUS="\u00ab Anterior";this.e.MSG_NEXT="Pr\u00f3xima \u00bb";this.e.MSG_NEWER="\u00ab Mais recentes";this.e.MSG_OLDER="Mais antigos \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Aceitar tudo";this.e.MSG_HELP_FRIENDREQUEST="Voc\u00ea e seus amigos ver\u00e3o uns aos outros em todos os sites do Google Friend Connect.";
this.e.MSG_HELP_FRIENDINVITE="Depois de se tornarem amigos, voc\u00eas ver\u00e3o um ao outro em todos os sites do Google Friend Connect.";this.e.MSG_HELP_BLOCKMEMBER="Bloquear um visitante o remove da lista de membros e impede que ele interaja com outros visitantes no seu site";this.e.MSG_INVITATION="Convite:";this.e.MSG_SEND="Enviar";this.e.MSG_BLOCK="Bloquear";this.e.MSG_IGNORE="Ignorar";this.e.MSG_CANCEL="Cancelar";this.e.MSG_SITE_SETTINGS="Configura\u00e7\u00f5es do site";this.e.MSG_ABOUT_FC=
"Sobre o Google Friend Connect";this.e.MSG_ALREADY_MEMBER="J\u00e1 \u00e9 um membro?";this.e.MSG_EDIT_PROFILE="Editar perfil"};gfc_7[gfc_].oa={};
gfc_7[gfc_].Br=function(){this.oa.MSG_SITE_MEMBERS="Seguidores";this.oa.MSG_NO_SITE_MEMBERS="Ainda n\u00e3o h\u00e1 seguidores.";this.oa.MSG_SHOW_BLOCKED="Mostrar seguidores bloqueados \u00bb";this.oa.MSG_SHOW_ALL="\u00ab Mostrar todos os seguidores";this.oa.MSG_ALL_SITE_MEMBERS="Todos os seguidores";this.oa.MSG_ALL_BLOCKED_MEMBERS="Todos os seguidores bloqueados";this.oa.MSG_NO_BLOCKED_MEMBERS="Voc\u00ea n\u00e3o bloqueou nenhum seguidor";this.oa.MSG_LIKE_THIS_SITE="Gostou deste blog?";this.oa.MSG_JOIN=
"Seguir";this.oa.MSG_BACK_TO_TOP="Membros";this.oa.MSG_JFJ="Participe e conecte-se aos seus amigos!";this.oa.MSG_HELP_FRIENDREQUEST="Voc\u00ea e seus amigos ver\u00e3o uns aos outros em todos os blogs que estiverem seguindo e sites do Google Friend Connect.";this.oa.MSG_HELP_FRIENDINVITE="Depois de se tornarem amigos, voc\u00eas ver\u00e3o um ao outro em todos os blogs que estiverem seguindo e sites do Google Friend Connect."};
gfc_7[gfc_].K=function(a,b){var c=!0;if(b[gfc_o]&&b[gfc_o].person){var d={},e=b[gfc_o].person[gfc_2b]()+" \u00e9 seu(sua) amigo(a)";d.MSG_IS_FRIEND=e;e="Voc\u00ea convidou "+(b[gfc_o].person[gfc_2b]()+" para ser seu(sua) amigo(a)");d.MSG_IS_INVITED=e;e="Amigos de "+b[gfc_o].person[gfc_2b]();d.MSG_PROFILE_FRIENDS=e;e="Todos os amigos de "+b[gfc_o].person[gfc_2b]();d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.g(a,f,d[f])}b.invitedBy&&b.invitedBy[gfc_2b]()&&(d=gfc_c[gfc_i]?gfc_c[gfc_i]:gfc_c[gfc_C][gfc_6c]+
2,c=(d-135)/8,d=(d-175)/8,c="Visualizar perfil de "+gfc__m(b.invitedBy[gfc_2b](),c),d=gfc__m(b.invitedBy[gfc_2b](),d)+" convidou voc\u00ea para este site",this.g(a,"MSG_VIEW_INVITER_PROFILE",c),this.g(a,"MSG_INVITED_YOU",d),this.nw=!0,c=!1);d=this.numWaitingMessages+" mensagens aguardando voc\u00ea.";this.isMessagingEnabled&&0<this.numWaitingMessages&&(c=!1,this.g(a,"showWaitingMessages",!0),this.isMessagingEnabled&&(this.g(a,"MSG_NUM_WAITING_MESSAGES",d),this.g(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING",
"Visualizar mensagens")));b.friendRequests&&(0<b.friendRequests[gfc_Qb]()&&(c=!1),d=1==b.friendRequests[gfc_Qb]()?"Solicita\u00e7\u00e3o de novo amigo \u00bb":"Solicita\u00e7\u00f5es de novos amigos ("+(b.friendRequests[gfc_Qb]()+") \u00bb"),this.g(a,"MSG_NEW_FRIEND_REQUESTS",d));if(this.lb){if(this.ql(this.lb.themeId))for(f in this.oa)this.g(a,f,this.oa[f]);this.lb.signInPrompt&&this.g(a,"MSG_JOIN",this.lb.signInPrompt);this.lb.signOutPrompt&&this.g(a,"MSG_SIGN_OUT",this.lb.signOutPrompt)}this.g(a,
"isViewerAdmin",b.isViewerAdmin);this.g(a,"isMessagingEnabled",this.isMessagingEnabled);this.g(a,"acceptMessages",this.Yn);this.g(a,"isViewingSelf",b.viewer&&b[gfc_o]&&b[gfc_o].person&&b.viewer[gfc_E]()==b[gfc_o].person[gfc_E]());d=!1;if(b.owner&&(e=b.owner[gfc_I]("profileExtensions")))for(f in e)d=!0;this.g(a,"communityHasProfile",d);this.g(a,"promoHtml",c?this.promoHtml:null);this.g(a,"insertHtml",function(a,b){gfc_Ka(a,b)})};gfc_7[gfc_].ql=function(a){return"blogger"==a};
gfc_7[gfc_].Xg=function(a,b,c,d){gfc_wn({id:a,text:b,version:this.ql(this.lb.themeId)?1:null,style:c},d)};
gfc_7[gfc_].P=function(a){function b(b,c){d.g(a,b,gfc_K(c,d))}this.g(a,"facesPerRow",this.Ub);for(var c in this.e)this.g(a,c,this.e[c]);var d=this;b("getThumbnail",this.xc);b("map",this.map);b("elide",gfc__m);b("safeSlice",this.wi);b("showAllActivities",this.Zv);b("transformActivity",this.gc);b("nextActivities",this.Fs);b("previousActivities",this.nt);b("showAllLinks",this.aw);b("transformLink",this.Mw);b("nextLinks",this.Js);b("previousLinks",this.pt);b("showAllSites",this.dw);b("transformSite",
this.Nw);b("nextSites",this.Qs);b("previousSites",this.vt);b("showAllMembers",this.bw);b("showBlockedMembers",this.fw);b("showUnblockedMembers",this.ww);b("nextMembers",this.Ks);b("nextBlockedMembers",this.Gs);b("previousMembers",this.qt);b("previousBlockedMembers",this.ot);b("showAllProfileFriends",this.cw);b("nextProfileFriends",this.Ps);b("previousProfileFriends",this.ut);b("showAllViewerFriends",this.ew);b("nextViewerFriends",this.Rs);b("previousViewerFriends",this.wt);b("isHome",this.Qh);b("goBack",
this.rh);b("goBackToHome",this.pw);b("editSettings",this.Db);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.On);b("blockUser",this.xj);b("unblockUser",this.Rw);b("goToInviteFriend",this.Hq);b("sendMessageDialog",this.wv);b("goToBlockMember",this.Gq);b("goToEditProfile",this.Db);b("goToViewerProfile",this.Iq);b("sendInvite",this.vv);b("blockMember",this.uo);b("acceptFriendRequest",this.Xn);b("ignoreFriendRequest",this.Ar);b("viewFriendRequests",this.Zw);b("acceptAllFriendRequests",
this.Wn);b("numPreviewFriends",this.oq);b("numPreviewMembers",this.pq);b("showInvitedBy",this.vq)};
gfc_7[gfc_].Kk=function(a){a=gfc_d.max(1,a?this.rc-1:this.rc);var b=this.d[gfc_k].members?this.d[gfc_k].members[gfc_Qb]():0,c=this.d[gfc_k].friends?this.d[gfc_k].friends[gfc_Qb]():0,b=gfc_d[gfc_co](b/this.Ub),c=gfc_d[gfc_co](c/this.Ub);b>gfc_d[gfc_co](a/2)?c>gfc_d[gfc_5a](a/2)?(b=gfc_d[gfc_co](a/2),c=gfc_d[gfc_5a](a/2)):b=gfc_d.max(0,a-c):c>gfc_d[gfc_5a](a/2)&&(c=gfc_d.max(0,a-b));b*=this.Ub;c*=this.Ub;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].pq=function(a){return this.Kk(a).numMembers};
gfc_7[gfc_].oq=function(a){return this.Kk(a).numFriends};gfc_7[gfc_].Ku=function(a,b){var c=gfc_e[gfc_H](),d={},e=gfc_e[gfc_D][gfc_Vc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_t];d[e.MAX]=b.pageSize?b.pageSize:this.la;var f=[gfc_e[gfc_x][gfc_q].ID,gfc_e[gfc_x][gfc_q][gfc_0a],gfc_e[gfc_x][gfc_q][gfc_Eb]];d[e[gfc_lc]]=f;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_8c];c.add(c[gfc_$b](gfc_if(),d),"ownerFriends");c[gfc_n](a)};
gfc_7[gfc_].Gt=function(a){this.d[gfc_k].members=a.get("ownerFriends")[gfc_l]()};gfc_7[gfc_].Eu=function(a,b){var c=gfc_e[gfc_H](),d={},e=gfc_e[gfc_D][gfc_Vc];d[e.FIRST]=b[gfc_t];d[e.MAX]=b.pageSize?b.pageSize:this.la;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_8c];e={};e[gfc_e[gfc_Kb][gfc_q][gfc_1b]]=gfc_e[gfc_Kb].PersonId.OWNER;e[gfc_e[gfc_Kb][gfc_q][gfc_Wb]]="BLOCKED";e[gfc_e[gfc_Kb][gfc_q][gfc_zc]]=1;e=gfc_e[gfc_vc](e);c.add(c[gfc_$b](e,d),"blockedMembers");c[gfc_n](a)};
gfc_7[gfc_].Ct=function(a){this.d[gfc_k].blockedMembers=a.get("blockedMembers")[gfc_l]()};gfc_7[gfc_].Qu=function(a,b){var c=gfc_e[gfc_H](),d=b&&b.person&&b.person[gfc_E]()||this.v[gfc_o].person[gfc_E](),e={},f=gfc_e[gfc_D][gfc_Vc];e[f.FIRST]=b[gfc_t];e[f.MAX]=b.pageSize?b.pageSize:this.la;d=this.Wl(d);e[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_8c];c.add(c[gfc_$b](d,e),"profileFriends");c[gfc_n](a)};
gfc_7[gfc_].Wl=function(a){var b={};b[gfc_e[gfc_Kb][gfc_q][gfc_1b]]=a;b[gfc_e[gfc_Kb][gfc_q][gfc_Wb]]="FRIENDS";b[gfc_e[gfc_Kb][gfc_q][gfc_zc]]=1;return gfc_e[gfc_vc](b)};gfc_7[gfc_].Lt=function(a){this.d[gfc_k][gfc_o].friends=a.get("profileFriends")[gfc_l]()};gfc_7[gfc_].pj=function(a){for(var b=gfc_e[gfc_k].getDataContext(),c=0;c<a[gfc_B];c++){var d=a[c],d=b.getDataSet(d);if(!d||d.code)return!1}return!0};
gfc_7[gfc_].Lu=function(a){var b=this.la,c=!b||24==b;c&&gfc_e[gfc_k]&&this.pj(["ownerFriends","viewer","siteSettings","friendRequests"])?a(gfc_e[gfc_k].getDataContext()[gfc_l]()):(c=gfc_bo.newBatch(),b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"},c.add("ownerFriends",gfc_bo.people.get(b)),c.add("viewer",gfc_bo.people.getViewer()),c.add("siteSettings",gfc_bo.extensions.get({command:"GetSiteSettings"})),c.add("friendRequests",gfc_bo.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'})),(b=gfc_ca().psinvite)&&c.add("invitedBy",gfc_bo.extensions.get({command:"DecodeInvitation",params:{token:b}})),c.execute(a))};gfc_7[gfc_].Ht=function(a,b){this.d[gfc_k].members=gfc_af(a.ownerFriends,gfc_6e);this.d[gfc_k].viewer=gfc_6e(a.viewer);this.nm(a,b,!0);this.lb=a[gfc_Wc];var c=gfc_ca();!c.psinvite||null!=this.d[gfc_k].viewer&&""!=this.d[gfc_k].viewer||(a.invitedBy&&(a.invitedBy.nickname=a.invitedBy.displayName),this.d[gfc_k].invitedBy=new gfc_e[gfc_x](a.invitedBy))};
gfc_7[gfc_].cv=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_t]||0==b[gfc_t],e=!c||20==c;d&&e&&gfc_e[gfc_k]&&this.pj(["friends","isViewerAdmin"])?a(gfc_e[gfc_k].getDataContext()[gfc_l]()):(d=gfc_bo.newBatch(),c={userId:"@viewer",groupId:"@friends",count:c},b[gfc_t]&&(c.startIndex=b[gfc_t]),d.add("friends",gfc_bo.people.get(c)),d.add("isViewerAdmin",gfc_bo.people.get({userId:"@viewer",groupId:"ADMINS"})),d.execute(a))};
gfc_7[gfc_].Rt=function(a){var b=a.friends;b&&!b[gfc_xc]&&(this.d[gfc_k].friends=gfc_af(b,gfc_6e));this.Tm(a)};gfc_7[gfc_].dv=function(a){var b=gfc_e[gfc_H]();b.add(gfc_9e("VIEWER"),"numWaitingMessages");b[gfc_n](a)};gfc_7[gfc_].Tt=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_l]().numberOfWaitingMessages};
gfc_7[gfc_].Su=function(a){this.log("requesting promo");var b=new gfc_a[gfc_Kc],b=b.getLang()+(b[gfc_rd]()?"_"+b[gfc_rd]():""),c=gfc_e[gfc_H]();c.add(gfc_Ze("GetPromo",{hl:b}),"promo");c[gfc_n](a)};gfc_7[gfc_].Nt=function(a){this.log("processing promo");(a=a.get("promo")[gfc_l]())&&-1!=a.promoCode&&(this.promoCode=a.promoCode,this.promoHtml=a.promoHtml)};
gfc_7[gfc_].io=function(){for(var a=function(){this.promoHtml=null;for(var a=gfc_$f("div","fc-promo-main",gfc_P("peg")),b=0;b<a[gfc_B];b++)gfc_7h(a[b],!1);this.X();this.log("Dismissing promo "+this.promoCode);a=gfc_e[gfc_H]();a.add(gfc_Ze("DismissPromo",{promoCode:this.promoCode}));a[gfc_n](gfc_K(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_$f("a","fc-promo-dismiss-link",gfc_P("peg")),c=0;c<b[gfc_B];c++){var d=b[c],e="click";gfc_ij(d,e);gfc_9i(d,e,gfc_K(a,this))}};
gfc_7[gfc_].Tm=function(a){var b=a.isViewerAdmin;b&&!b[gfc_xc]?this.d[gfc_k].isViewerAdmin=b.list[gfc_B]:a.get&&a.get("isViewerAdmin")&&(a=a.get("isViewerAdmin"))&&!a[gfc_Jc]()&&(this.d[gfc_k].isViewerAdmin=a[gfc_l]()[gfc_Qb]())};gfc_7[gfc_].Wn=function(a){var b=[];a.each(function(a){a={user:a[gfc_I](goog.opensocial.peoplesense.Invite[gfc_q].INVITER)[gfc_E](),action:"ACCEPT"};b[gfc_v](a)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.Dg,this),{friendRequestResponses:b})};
gfc_7[gfc_].pw=function(){this.ea();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].Xn=function(a){a={user:a[gfc_E](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.Dg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Zw=function(){this.ea();this.B("friend-requests")};gfc_7[gfc_].On=function(a){this.Jb()?(this.ea(),this.ax(a)):gfc_We(a[gfc_E]())};
gfc_7[gfc_].ax=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].Yu=function(a,b){var c=gfc_e[gfc_H](),d=gfc_e[gfc_D][gfc_Vc],e={};e[d.FIRST]=b&&b[gfc_t]?b[gfc_t]:0;var f=this.d[gfc_k][gfc_o].person[gfc_E]();e[d.MAX]=this.tn;c.add(gfc_ff(gfc_e[gfc_vc]({userId:f}),e),"profileSites");c[gfc_n](a)};gfc_7[gfc_].Pt=function(a){this.d[gfc_k][gfc_o].sites=a.get("profileSites")[gfc_l]()};
gfc_7[gfc_].Pu=function(a,b){this.d[gfc_k].profile={};b=b||{};var c=b.person,d={},c=c[gfc_E](),e=gfc_e[gfc_H](),f=[gfc_e[gfc_x][gfc_q].ID,gfc_e[gfc_x][gfc_q][gfc_0a],gfc_e[gfc_x][gfc_q][gfc_Eb],gfc_e[gfc_x][gfc_q].ABOUT_ME,gfc_e[gfc_x][gfc_q].URLS,"profileExtensions"],g=gfc_e[gfc_D][gfc_Vc];d[g[gfc_lc]]=f;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_8c];e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_df("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.lb||e.add(gfc_8e(),"siteSettings");e.add(gfc_df(c,"ADMINS"),"isAdmin");e.add(gfc_df(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_9e(c),"canMessage");e[gfc_n](a)};
gfc_7[gfc_].Jf=function(a,b){var c=b.person[gfc_E](),d=gfc_e[gfc_vc]({userId:c}),e=gfc_e[gfc_H]();(this.d[gfc_k].viewer&&c!=this.d[gfc_k].viewer[gfc_E]()||this.Jb())&&e.add(gfc_cf(b.person[gfc_E](),"VIEWER"),"isProfileFriend");e.add(e[gfc_bd](d,{}),"activities");e[gfc_n](a)};
gfc_7[gfc_].hd=function(a,b){null!=a.get("activities")[gfc_l]()&&(this.d[gfc_k][gfc_o].activities=a.get("activities")[gfc_l]());var c=a.get("isProfileFriend");c&&b&&null!=this.d[gfc_k].viewer&&this.d[gfc_k].viewer[gfc_E]()!=b.person[gfc_E]()&&(this.d[gfc_k][gfc_o].isFriend=c[gfc_l]()[gfc_w])};
gfc_7[gfc_].Kt=function(a,b){var c=a.get("profile")[gfc_l]();this.d[gfc_k][gfc_o].person=c;this.d[gfc_k][gfc_o].person.externalProfileUrl=null;var d=c[gfc_I](gfc_e[gfc_x][gfc_q].URLS),e=[];if(d)for(var f=0;f<d[gfc_B];f++){var g=d[f];"profile"!=g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&"externalProfile"!=g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&e[gfc_v](g);"externalProfile"==g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&(this.d[gfc_k][gfc_o].person.externalProfileUrl=g[gfc_I](gfc_e.Url[gfc_q].ADDRESS))}this.d[gfc_k][gfc_o].links=
new gfc_fo(e,this.rf,0);this.d[gfc_k].owner=a.get("owner")[gfc_l]();this.d[gfc_k].viewer=a.get("viewer")[gfc_l]();(d=this.d[gfc_k].viewer)&&b.person[gfc_E]()!=this.d[gfc_k].viewer[gfc_E]()&&(this.d[gfc_k][gfc_o].isAdmin=a.get("isAdmin")[gfc_l](),this.d[gfc_k][gfc_o].isAdmin&&(this.d[gfc_k][gfc_o].isAdmin=this.d[gfc_k][gfc_o].isAdmin[gfc_Qb]()),this.d[gfc_k][gfc_o].isBlocked=a.get("isBlocked")[gfc_l](),this.d[gfc_k][gfc_o].isBlocked&&(this.d[gfc_k][gfc_o].isBlocked=this.d[gfc_k][gfc_o].isBlocked[gfc_Qb]()));
c=c[gfc_I]("profileExtensions");c=this.Nb.jf(c,this.Nb.Oi);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=!1;if("SHORT_TEXT"==e[gfc_4c]||"LONG_TEXT"==e[gfc_4c])e[gfc_w]&&e[gfc_w][gfc_Ec]&&(g.body=[],g[gfc_C][gfc_v](e[gfc_w][gfc_Ec]),h=!0);else if(e[gfc_w]&&e[gfc_w].choice&&0<e[gfc_w].choice[gfc_B]){g.body=[];for(h=0;h<e[gfc_w].choice[gfc_B];++h)g[gfc_C][gfc_v](e[gfc_w].choice[h][gfc_pc]);h=!0}h&&d[gfc_v](g)}this.d[gfc_k][gfc_o].profileExtensions=d;this.lb||(this.lb=a.get("siteSettings")[gfc_l]());
this.isMessagingEnabled&&(f=(f=a.get("canMessage"))&&f[gfc_l]().canSendMessage,this.d[gfc_k][gfc_o].canSendMessage=f);this.Tm(a)};gfc_7[gfc_].xj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].Rw=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[],d=gfc_K(function(a,b,c){a[gfc_v](b(c))},this,c,b);a.each(d);return c};gfc_7[gfc_].bw=function(){this.ea();this.B("members-page")};
gfc_7[gfc_].fw=function(){this.ea();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].ww=function(){this.Xi()};gfc_7[gfc_].Ks=function(a){this.render(["member-page"],"members-page",{start:this.la+a.getOffset()})};gfc_7[gfc_].qt=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.la})};gfc_7[gfc_].Gs=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.la+a.getOffset()})};
gfc_7[gfc_].ot=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.la})};gfc_7[gfc_].ew=function(){this.ea();this.B("viewer-friends-page")};gfc_7[gfc_].Rs=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.la+a.getOffset()})};gfc_7[gfc_].wt=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.la})};gfc_7[gfc_].cw=function(){this.ea();this.B("profile-friends-page")};
gfc_7[gfc_].Ps=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.la+a.getOffset(),person:this.d[gfc_k][gfc_o].person})};gfc_7[gfc_].ut=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.la,person:this.d[gfc_k][gfc_o].person})};gfc_7[gfc_].aw=function(){this.ea();this.B("links")};gfc_7[gfc_].Js=function(a){var b=this.rf+a.getOffset();this.d[gfc_k][gfc_o].links=new gfc_fo(a.all(),this.rf,b);this.B("links")};
gfc_7[gfc_].pt=function(a){var b=a.getOffset()-this.rf;this.d[gfc_k][gfc_o].links=new gfc_fo(a.all(),this.rf,b);this.B("links")};gfc_7[gfc_].dw=function(){this.ea();this.B("sites")};gfc_7[gfc_].Qs=function(a){this.render(["sitesData"],"sites",{start:this.tn+a.getOffset()})};gfc_7[gfc_].vt=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.tn})};gfc_7[gfc_].Zv=function(){this.ea();this.B("activities")};
gfc_7[gfc_].Fs=function(a){this.render(["activityData"],"activities",{start:this.Ba+a.getOffset()})};gfc_7[gfc_].nt=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Ba})};gfc_7[gfc_].$e=function(a){this.render(["deleteActivity"],this.d[gfc_hd],{activity:a})};gfc_7[gfc_].Du=function(a,b){var c=gfc_e[gfc_H]();c.add(gfc_ef(b.person[gfc_E](),["BLOCKED"],[]),"block");this.bd();c[gfc_n](a)};
gfc_7[gfc_].Bt=function(a){if(a=!a.get("block")[gfc_Jc]())this.d[gfc_k][gfc_o].isBlocked=!0};gfc_7[gfc_].av=function(a,b){var c=gfc_e[gfc_H]();c.add(gfc_ef(b.person[gfc_E](),[],["BLOCKED"]),"unblock");this.bd();c[gfc_n](a)};gfc_7[gfc_].Qt=function(a){if(a=!a.get("unblock")[gfc_Jc]())this.d[gfc_k][gfc_o].isBlocked=!1};
gfc_7[gfc_].Kf=function(a,b){var c=b.activity,d=c[gfc_I](gfc_e[gfc_bc][gfc_q].ID),c=gfc_e[gfc_vc]({userId:c[gfc_I](gfc_e[gfc_bc][gfc_q][gfc_1b])}),e=gfc_e[gfc_H]();e.add(gfc__e(d),"delete");e.add(e[gfc_bd](c,{}),"activities");e[gfc_n](a)};
gfc_7[gfc_].gc=function(a){var b=gfc_Fn,c=function(a){return a=a[gfc_j](/<a/g,"<a target='_top'")},d=null,e=this.d[gfc_k].viewer;null!=e&&a[gfc_I](gfc_e[gfc_bc][gfc_q][gfc_1b])==this.d[gfc_k].viewer[gfc_E]()&&(d=gfc_K(this.$e,this,a));(e=a[gfc_I](gfc_e[gfc_bc][gfc_q].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_b.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_ga(a[gfc_I](gfc_e[gfc_bc][gfc_q].POSTED_TIME))),link:a[gfc_I](gfc_e[gfc_bc][gfc_q].STREAM_URL,{escapeType:"none"}),siteTitle:a[gfc_I](gfc_e[gfc_bc][gfc_q].STREAM_TITLE,
{escapeType:"none"}),innerHTML:c(a[gfc_I](gfc_e[gfc_bc][gfc_q].TITLE,{escapeType:"none"})),body:c(a[gfc_I](gfc_e[gfc_bc][gfc_q].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].Nw=function(a){var b=gfc_a[gfc_hc].unescapeString,c=gfc_do;return{icon:c(a[gfc_I](gfc_e[gfc_x][gfc_q][gfc_Sc])),link:a[gfc_I](gfc_e[gfc_x][gfc_q][gfc_Sc]),title:b(a[gfc_2b]())}};
gfc_7[gfc_].Mw=function(a){var b=gfc_a[gfc_hc].unescapeString,c=gfc_do,d=a[gfc_I](gfc_e.Url[gfc_q].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_I](gfc_e.Url[gfc_q].LINK_TEXT))||d}};gfc_7[gfc_].Ru=function(a,b){var c=gfc_e[gfc_H](),d=b.person[gfc_E](),e=gfc_e[gfc_D][gfc_Vc],f=this.Wl(d),g={};g[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_8c];c.add(c[gfc_$b](f,g),"friends");f={};f[e.FIRST]=this.ly;f[e.MAX]=this.ky;c.add(gfc_ff(gfc_e[gfc_vc]({userId:d}),f),"profileSites");c[gfc_n](a)};
gfc_7[gfc_].Ar=function(a){a={user:a[gfc_E](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_K(this.Dg,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Dg=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].Xu=function(a,b){var c=b[gfc_o],d=gfc_e[gfc_H]();d.add(gfc_0e(c[gfc_E](),b.message),"friendRequest");this.bd();d[gfc_n](a)};gfc_7[gfc_].Ot=function(a){a.get("friendRequest")[gfc_Jc]()||(this.d[gfc_k][gfc_o].isInvited=!0)};
gfc_7[gfc_].Hu=function(a,b){var c=gfc_bo.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_bo.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_a[gfc_ec].stringify(d)+"}"}));c.add("friendRequests",gfc_bo.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.bd();c.execute(a)};gfc_7[gfc_].Hq=function(){this.ea();this.B("invite-friend")};gfc_7[gfc_].wv=function(a){this.isMessagingEnabled&&(a=a[gfc_I](gfc_e[gfc_x][gfc_q].ID),this.xv(a))};
gfc_7[gfc_].xv=function(a){this.isMessagingEnabled&&(a="/friendconnect/messaging/compose?recipientId="+a,gfc_on(a,"570","395"))};gfc_1[gfc_].Yn=function(){gfc_on("/friendconnect/messaging/accept","570","375");return!1};gfc_7[gfc_].Gq=function(){this.ea();this.B("block-member")};gfc_7[gfc_].Iq=function(){this.On(this.d[gfc_k].viewer)};gfc_7[gfc_].vv=function(a){this.yf();a={profile:a};var b=gfc_P("inviteMessage");b&&(a.message=gfc_qh(b));this.render(["sendFriendRequest"],"profile",a)};
gfc_7[gfc_].uo=function(a){this.yf();this.xj(a)};gfc_7[gfc_].nm=function(a,b,c){c=c||!1;this.d[gfc_k].friendRequests=gfc_af(a.friendRequests,gfc_2e);0<this.d[gfc_k].friendRequests[gfc_Qb]()?b["next-view"]="friend-requests":b["next-view"]="faces";c||gfc_$m("friend")};gfc_7[gfc_].Mt=function(a){this.d[gfc_k][gfc_o].sites=a.get("profileSites")[gfc_l]();this.d[gfc_k][gfc_o].friends=a.get("friends")[gfc_l]()};gfc_7[gfc_].vq=function(){return this.nw};
gfc_7[gfc_].X=function(){this.Hx.rebuild();this.io();gfc_a[gfc_3c].adjustHeight()};gfc_7[gfc_].et=function(a){return a=gfc_Q("span",{"class":"fc-cap-link-big"},gfc_Q("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Hg())};
gfc_7[gfc_].dt=function(){var a=[];a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);this.isSocialShareEnabled&&(a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE));this.d[gfc_k].isViewerAdmin&&!this.Jb()&&(a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE));a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-signout"},this.lb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_B]]=
gfc_Q("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_Q("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].ft=function(a){a[gfc_Zb]();a=a[gfc_F].h()[gfc_5c];a[gfc_gb]("menuaction-settings")?this.Db():a[gfc_gb]("menuaction-share")?this.share():a[gfc_gb]("menuaction-signout")?this.signout():a[gfc_gb]("menuaction-manage")?this.Mq():a[gfc_gb]("menuaction-aboutfc")&&(a=gfc_b[gfc_Bc](gfc_gn()+"/friendconnect/home/overview"),a[gfc_mb]())};gfc_7[gfc_].Mq=function(){var a={},b=gfc_a[gfc_r][gfc_6a]()[gfc_rc];gfc_$m("lightbox");gfc_a[gfc_r].requestNavigateTo(b,a);return!1};
var gfc_eo=function(a){for(var b={},c=0;c<a[gfc_B];++c)b[a[c]]=a[c];return b}("HEIGHT BORDER_COLOR CONTENT_BG_COLOR CONTENT_HEADLINE_COLOR CONTENT_LINK_COLOR CONTENT_SECONDARY_TEXT_COLOR CONTENT_SECONDARY_LINK_COLOR CONTENT_TEXT_COLOR ENDCAP_BG_COLOR ENDCAP_LINK_COLOR ENDCAP_TEXT_COLOR FACE_SIZE NUMBER_ROWS".split(" "));
gfc_7[gfc_].s=function(){var a=gfc_eo,b=[],c=0;this.f(a.HEIGHT);this.Th()&&(b[c++]=this.j(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE)));b[c++]=this.j(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.Pm);b[c++]=this.j(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));this.gf()&&(this.al("profile")?b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n":this.Wh()?b[c++]=".fc-topcap {height: 0px;}\n":b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n");this.Jb()?b[c++]=".fc-userpic-caption {margin-left: 59px;}\n":b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";this.Wh()?b[c++]=".fc-topcap-color {background-color: white;}\n":b[c++]=this.j(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));this.rl()?b[c++]=
".fc-botcap-short {background-color: white;}\n":b[c++]=this.j(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",this.f(a.ENDCAP_TEXT_COLOR));
b[c++]=this.j(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.j(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.j(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.j(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.j(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.j(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.j(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_7.i.s[gfc_G](this)+b[gfc_J]("\n")};gfc_L("goog.peoplesense.gadget.Members",gfc_7);gfc_L("goog.peoplesense.gadget.Members.start",gfc_7[gfc_t]);var gfc_fo=function(a,b,c){gfc_e.Collection[gfc_G](this,a[gfc_Gc](c,c+b),c,a[gfc_B]);this.kx=a;this.da=b};gfc_fo.inherits(gfc_e.Collection);gfc_fo[gfc_].all=function(){return this.kx};gfc_fo[gfc_].rb=function(){return this.da};gfc_L("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_fo[gfc_].all);
gfc_L("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_fo[gfc_].rb);
